# Generated by Django 3.2.9 on 2021-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='new',
            field=models.TextField(blank=True, null=True),
        ),
    ]
