# Generated by Django 3.2.9 on 2021-11-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new',
        ),
    ]
